ChatPrefix: "&b&lBl&9&lue&1&lMC &0» "

Messages:
  # {amount}
  Redeemed: "&3You have successfully redeemed {amount} MobCoins"
  OtherBalance: "3{PLAYER}'s balance is &b{amount}"
  Balance: "&3Your balance is &b{amount}"

Coin:
  Item: SUNFLOWER
  Glowing: true
  Name: "&9&k&l| &4&lMob&c&lCoin &9&k&l|"
  lore:
  - '&7Earn &4Mob&cCoins &7from mobs'
  - '&7and spend them in mobcoin shop'